### ISSUE TITLE
Support for /view URLs on static hosting

### ISSUE THREAD

**Issue by dgfitch** [pingcap/gdocwiki#157]
Hey Greg and co, we're likely going to start using this and contributing some features back.

But we're trying to host it statically (doing `BUILD_PATH=.../pub_html npm run build`) and one thing I'm unclear on is how the `/view/:id` URLs are intended to work on static hosting. (Maybe they're not.)

Is there some kind of URL rewriting I can do on the backend, such that requests for `/view...` land the user at loading index.html with the appropriate parameters? Or is it intended that an actual server-side app needs to be running? I'm not a React expert, and the README on gdocwiki doesn't really specify that much detail about a "production" deployment of this.

It's way cool though! Dang!

**Comment by hohno-panopto** [comment]
I also want to say thanks to Greg and the team to make this application open source!

I deployed this application by using AWS S3 + CloudFront and hit the same issue as Dan.
I researched the Internet and I was able to resolve my situation by [this article](https://blog.nicera.in/2020/08/hosting-react-app-on-s3-cloudfront-with-react-router-404-fix/).
For my specific configuration;
1. I needed to setup CF custom error not for `404`, but for `403`.
2. I did not need to modify S3 configuration because my system does not allow direct access to S3 and `Static website hosting` is disabled.

Note that I hit several articles for other environments by searching `react router static hosting`. Those may help others.

**Comment by breezewish** [comment]
gdocwiki is a pure static application that does not need server side rendering.

In our deployment, we added a fallback rule that will turn every access to non-exist (404) static files into the `index.html`. The browser will receive exactly the same HTTP response when accessing `/view/{anything}` and `/`. When there is a self hosted server, this can be easily achieved by "rewriter rules" like https://stackoverflow.com/questions/43951720/react-router-and-nginx

I do agree that we need some instructions about how to deploy it in some popular platforms, so that non-web experts can use it easier. Maybe deploying to the following platforms can be introduced:

- AWS
- Cloudflare
- Netlify
- Vercel

Meanwhile, please refer to these documentations that could be helpful to you (this is called SPA architecture):

- AWS: https://dev.to/alexeyromanchenko/how-to-deploy-spa-as-a-static-website-using-aws-s3-1adg
- Cloudflare: Looks like Cloudflare Pages supports SPA: https://developers.cloudflare.com/pages/platform/serving-pages/

**Comment by dgfitch** [comment]
For those on nginx, the fix is just including `index.html` in your try_files line in the nginx config, like so:

    try_files $uri $uri/ /index.html =404;
